server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personaldb
    username: personal
    password: 4555
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always

jwt:
  secret: blabla
  username: admin
  password: $2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6 #password: password